### GET CHAMPION

GET localhost:8080/api/warframes

### CREATE CHAMPION

POST localhost:8080/api/warframes
Content-Type: application/json

{
  "name": "xerath",
  "role": "mage",
  "difficulty": "hard"
}

### UPDATE CHAMPION

PATCH localhost:8080/api/warframes/xerath
Content-Type: application/json

{
  "abilities": ["ray"]
}

### DELETE CHAMPION

DELETE localhost:8080/api/warframes/xerath